name: Entry Request
description: Request for a single new entry or term.
title: "[Entry] Subject : Entry Name"
labels: ["new entry"]
assignees: "Name here"
body:
  - type: markdown
    attributes:
      value: Please refer to the [Contributing Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) before submitting a PR.
  - type: dropdown
    id: entries
    attributes:
      label: Entry Type (select all that apply)
      multiple: true
      options:
        - New Subject with Entries/Terms
        - New Entry for Existing Subject
        - New Term for Existing Entry
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow Codecademy Doc's Code of Conduct
          required: true
  - type: checkboxes
    id: maintainers
    attributes:
      label: For Maintainers
      options:
        - label: Labels added
          required: true
        - label: Issue is assigned
          required: false